version: '2.4'

services:
  right-consents-mail:
    image: maildev/maildev
    container_name: right-consents-mail
    command: bin/maildev --outgoing-host smtp.gmail.com --outgoing-port 465 --outgoing-user XXXXXXXXXXXXXXXx --outgoing-pass XXXXXXXXXXXXXXXx
    ports:
      - 4288:1080
    healthcheck:
      test: ["CMD", "wget", "-q", "http://127.0.0.1:1080", "-O", "/dev/null"]
      interval: 5s
      retries: 200
      timeout: 5s
  right-consents-auth:
    container_name: right-consents-auth
    image: jboss/keycloak:11.0.3
    restart: unless-stopped
    environment:
      KEYCLOAK_IMPORT: /opt/jboss/keycloak/imports/right-consents.json
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_USER: admin
    volumes:
      - auth-data:/opt/jboss/keycloak/standalone/data
      - ./imports:/opt/jboss/keycloak/imports
    ports:
      - 4285:8080
    healthcheck:
      test: ["CMD", "/usr/bin/curl", "-q", "-s", "http://127.0.0.1:8080/auth/realms/master/.well-known/openid-configuration", "-o", "/dev/null"]
      interval: 5s
      retries: 200
      timeout: 5s
    depends_on:
      right-consents-mail:
        condition: service_healthy
  right-consents-back:
    container_name: right-consents-back
    restart: unless-stopped
    image: fairandsmart/consent-manager-back:2.4.0
    ports:
      - 4287:8087
    environment:
      FS_AUTH_BACK_URL: http://right-consents-auth:8080
      FS_AUTH_FRONT_URL: http://localhost:4285
      FS_GUI_URL: http://localhost:4286
      FS_INSTANCE_LANG: ${FS_INSTANCE_LANG:-en}
      FS_INSTANCE_IMPORT_DATA: ${FS_INSTANCE_IMPORT_DATA:-true}
      FS_MAILER_HOST: right-consents-mail
      FS_MAILER_PORT: 1025
      FS_PUBLIC_URL: http://localhost:4287
      # Bypass token issuer verification. Mandatory only when testing the android application 
      quarkus.oidc.token.issuer: any
    depends_on:
      right-consents-auth:
        condition: service_healthy
      right-consents-mail:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "/usr/bin/curl", "-q", "-s", "http://127.0.0.1:8087/q/health", "-o", "/dev/null"]
      interval: 5s
      retries: 200
      timeout: 5s
    volumes:
      - back-data:/data
  right-consents-gui:
    container_name: right-consents-gui
    restart: unless-stopped
    image: fairandsmart/consent-manager-gui:2.4.0
    environment:
      FS_AUTH_URL: http://localhost:4285/auth
      FS_GUI_URL: http://localhost:4286
      FS_MANAGER_URL:  http://localhost:4287
      FS_MANAGER_PRIVATE_URL:  http://right-consents-back:8087
    ports:
      - 4286:80
    healthcheck:
      test: ["CMD", "/usr/bin/curl", "-q", "-s", "http://127.0.0.1:80", "-o", "/dev/null"]
      interval: 5s
      retries: 200
      timeout: 5s
    depends_on:
      right-consents-back:
        condition: service_healthy
volumes:
  auth-data:
  back-data:
